# Generated by Django 5.0.2 on 2025-05-29 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_notice'),
    ]

    operations = [
    ]
