# Generated by Django 5.0.2 on 2025-05-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_organizingcommitteemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizingcommitteemember',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
