# Generated by Django 5.0.2 on 2025-05-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
