# Generated by Django 5.0.2 on 2025-05-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_profileframesubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('name', models.CharField(max_length=255)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['batch', 'name'],
            },
        ),
    ]
