# Generated by Django 5.0.2 on 2025-06-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileframesubmission',
            name='batch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profileframesubmission',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
