# Generated by Django 5.0.2 on 2025-06-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_guest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': [models.Case(models.When(role='প্রধান অতিথি', then=0), models.When(role='বিশেষ অতিথি', then=1), models.When(role='সভাপতিত্ব', then=2), models.When(role='সার্বিক ত্বত্তবধান', then=3), default=4, output_field=models.IntegerField()), 'name']},
        ),
    ]
