services:
  - type: web
    name: reunion-backend-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn reunion_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 8000
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: reunion-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://reunion-event-client.vercel.app
      - key: RENDER_EXTERNAL_HOSTNAME
        value: reunion-backend-server.onrender.com
