services:
  - type: web
    name: reunion-backend-server
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn reunion_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: reunion-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://reunion-event-client.vercel.app
      - key: RENDER_EXTERNAL_HOSTNAME
        value: reunion-backend-server.onrender.com
